[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=43200,
      immutable'''
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"